occupations = {
1: 'Alewife  Rolling pin (close, awkward, 1 wt), cask of ale (2 rations, 2 wt)',
2: 'Apiarist     Staff (close, reach, 1 wt), 1d4 clay jars of honey (1 wt ea.)',
3: 'Apothecary  Sickle (close, messy, 1 wt), mortar & pestle (0 wt)',
4: 'Baker   Baking paddle (reach, awkward, 1 wt), sack of flour (2 wt)',
5: 'Bard    Knife (hand, 0 wt), instrument [roll 1d4: 1 = voice; 2 = flute (0 wt); 3 = lute (1 wt); 4 = horn (1 wt)] ',
6: 'Basketmaker Knife (hand, 0 wt), sturdy basket (1 wt)',
7: 'Beggar 1 begging bowl (0 wt), 1D4 coins',
8: 'Blacksmith   Hammer (close, 1 wt), burlap sack (0 wt), 1D4 iron ingots (1 wt ea.)',
9: 'Boatwright   Handaxe (close, 1 wt), 2D4 planks of wood (1 wt each)',
10: 'Bowyer  Shortbow (near, far, 1 wt), arrows (1 ammo, 1 wt), 1d4 sets of staves & sinews (1 wt ea.)',
11: 'Bricklayer    Trowel (close, awkward, 1 wt), hod (1 wt), 2d4 bricks (1 wt each)',
12: 'Burglar     Prybar (close, awkward, 1 wt), burlap sack (0 wt)',
13: 'Butcher  Cleaver (hand, messy, 1 wt), side of salted beef (4 rations, 2 wt)',
14: 'Carpenter    Handaxe (close, 1 wt), hand saw (1 wt)',
15: 'Cartwright   Handaxe (close, 1 wt), pushcart ',
16: 'Catchpole    Club (close, 2 wt), shoulder bag (0 wt), 2D6 coins ',
17: 'Chandler     Staff (close, 2-handed, 1 wt), 2D4 candles (0 wt)',
18: 'Chapman    Staff (close, 2-handed, 1 wt), rucksack (0 wt), trade item [roll 1d4: 1 = worthless baubles (0 wt); 2 = smoked fish (2 rations, 1 wt);     3 = adventuring gear (2 uses, 1 wt); 4 = jewelry (25 coins, 0 wt)] ',
19: 'Cheesemaker Staff (close, 2-handed, 1 wt), burlap sack (0 wt), wheel of cheese (4 rations, 2 wt)',
20: 'Cobbler  Tack hammer (hand, 0 wt), 1d4 pairs of shoes or boots (1 wt ea.)',
21: 'Constable    Shortsword (close, 1 wt), set of iron cuffs w/key (1 wt)',
22: 'Courier  Knife (hand, 0 wt), leather satchel (0 wt), important letter (0 wt)',
23: 'Crier    Knife (hand, 0 wt), plumed hat (worn, 0 wt)',
24: 'Crofter  Pitchfork (close, reach, 1 wt), bushel of crops (4 rations, 2 wt, roll 1D4: 1=turnips; 2=potatoes; 3=onions; 4=oats)',
25: 'Crofter  Pitchfork (close, reach, 1 wt), bushel of crops (4 rations, 2 wt, roll 1D4: 1=turnips; 2=potatoes; 3=onions; 4=oats)',
26: 'Crofter  Pitchfork (close, reach, 1 wt), bushel of crops (4 rations, 2 wt, roll 1D4: 1=turnips; 2=potatoes; 3=onions; 4=oats)',
27: 'Crofter  Pitchfork (close, reach, 1 wt), bushel of crops (4 rations, 2 wt, roll 1D4: 1=turnips; 2=potatoes; 3=onions; 4=oats)',
28: 'Ditch digger  Shovel (close, awkward, 2 wt)',
29: 'Dung carter  Shovel (close, awkward, 2 wt), pushcart full of dung ',
30: 'Dwarf miner Pick (close, +1 damage, 2 wt), adventuring gear (1d4 uses, 1 wt)',
31: 'Dwarf smith  Hammer (close, 1 wt), burlap sack (0 wt), 1d4 iron ingots (1 wt ea.)',
32: 'Dwarf mason Hammer (close, 1 wt), chisel (hand, awkward, 1 wt)',
33: 'Dwarf trapper    Knife (hand, 0 wt), burlap sack (0 wt), 1d4 mole traps (1 wt ea.)',
34: 'Elf hunter    Shortbow (near, far, 1 wt), arrows (1d4 ammo, 1 wt)',
35: 'Elf troubador Knife (hand, 0 wt), elven lyre (1 wt)',
36: 'Elf wanderer Staff (close, reach, 1 wt), hooded cloak (worn, 0 wt)',
37: 'Elf weaver   Knife (hand, 0 wt), bolt of silk (2 wt)',
38: 'Executioner  Executioner axe (close, 2-handed, messy, +1 damage, 2 wt) ,black hood (worn, 0 wt)',
39: 'Falconer Knife (hand, 0 wt), leather gauntlet (0 wt), falcon',
40: 'Ferry pilot   Club (close, 2 wt), 10ft pole ',
41: 'Fisherperson  Knife (hand, 0 wt), fishing net (reach, thrown)',
42: 'Fisherperson  Knife (hand, 0 wt), fishing net (reach, thrown)',
43: 'Fisherperson  Knife (hand, 0 wt), fishing net (reach, thrown)',
44: 'Fletcher     Shortbow (near, far, 1 wt), arrows (1d4 ammo, 1 wt)',
45: 'Footpad     Sap (hand, stun damage, 0 wt), burlap sack (0 wt)',
46: 'Forager  Sickle (hand, messy, 1 wt), burlap sack (0 wt), mushrooms     (1d4 rations, 1 wt)',
47: 'Forester     Shortbow (near, far, 1 wt), arrows (1d4 ammo, 1 wt)',
48: 'Goatherd Crook (reach, awkward, 1 wt), 1d4 goats',
49: 'Goatherd Crook (reach, awkward, 1 wt), 1d4 goats',
50: 'Goatherd Crook (reach, awkward, 1 wt), 1d4 goats',
51: 'Gravedigger Shovel (close, awkward, 2 wt)',
52: 'Halfling brewer Staff (close, 2-handed, 1 wt), cask of beer (2 rations, 2 wt)',
53: 'Halfling cook Cleaver (hand, +1 damage, 1 wt), meat pies (1d4 rations, 1 wt)',
54: 'Halfling crofter Pitchfork (close, reach, 1 wt), bushel of crop [2 wt, roll 1D4: 1 = turnips (4 rations); 2 = potatoes (4 rations); 3 =onions (4 rations), 4 =pipeweed]',
55: 'Halfling gardener Spade (hand, awkward, 0 wt), wheelbarrow',
56: 'Healer Staff (close, 2-handed, 1 wt), shoulder bag (0 wt), bandages (1d4 uses, slow, 0 wt)',
57: 'Hedge wizard Staff (close, 2-handed, 1 wt), belt pouch (0 wt), 1 cantrip [roll 1D6: 1-2 = Light; 3-4 = Unseen Servant; 5-6 = Prestidigitation]',
58: 'Herald Shortsword (close, 1 wt), trumpet (1 wt)',
59: 'Herbalist Staff (close, 2-handed, 1 wt), pouch (0 wt), poultices & herbs (1d4 uses, slow, 0 wt)',
60: 'Hunter Shortbow (near, far, 1 wt), arrows (1d4 ammo, 1 wt)',
61: 'Hunter Shortbow (near, far, 1 wt), arrows (1d4 ammo, 1 wt)',
62: 'Hunter Shortbow (near, far, 1 wt), arrows (1d4 ammo, 1 wt)',
63: 'Innkeeper Club (close, 2 wt), provisions (2d4 rations, 2 wt)',
64: 'Lantern maker Hammer (close, 1 wt), lantern (0 wt), flask of oil (0 wt), flint & steel (0 wt)',
65: 'Laundress Canvas sack (0 wt), cake of soap (0 wt)',
66: 'Miller Club (close, 2 wt), sack of flour (2 wt)',
67: 'Miner Pick (close, +1 damage, 2 wt), lantern (0 wt), flask of oil (0 wt), flint & steel (0 wt)',
68: 'Monk Staff (close, 2-handed, 1 wt), holy symbol (0 wt)',
69: 'Netmaker Knife (hand, 0 wt), fishing net (reach, thrown), 50ft of rope (2 wt)',
70: 'Noble Longsword (close, +1 damage, 1 wt), signet ring (10 coins, 0 wt)',
71: 'Oxherd Whip (reach, 1 wt), ox',
72: 'Peddler Knife (hand, 0 wt), rucksack (worn, 0 wt), trade item [roll 1D4: 1 = pots & pans (2 wt); 2 = 2d4 knives (hand, 0 wt), 3 = adventuring gear (1d4 uses, 2 wt), 4 = 1d4 healing potions (heal 1d8, 0 wt)]',
73: 'Pilgrim Staff (close, 2-handed, 1 wt), holy symbol (0 wt)',
74: 'Potter Club (close, 2 wt), burlap sack (0 wt), 5 lbs. of clay (2 wt)',
75: 'Prostitute Knife (hand, 0 wt), flask of perfume (0 wt)',
76: 'Rat catcher Club (close, 2 wt), burlap sack (0 wt), 2d4 dead rats (1 wt)',
77: 'Ropemaker Club (close, 2 wt), 100ft of rope (2 wt)',
78: 'Scout Knife (hand, 0 wt), cloak (worn, 0 wt)',
79: 'Scribe 2d4 pieces of parchment (0 wt), quill & bottle of ink (0 wt)',
80: 'Shepherd Crook (reach, awkward, 1 wt), 1d4 sheep',
81: 'Shepherd Crook (reach, awkward, 1 wt), 1d4 sheep',
82: 'Shepherd Crook (reach, awkward, 1 wt), 1d4 sheep',
83: 'Soothsayer Nothing',
84: 'Swineherd Crook (reach, awkward, 1 wt), 1d4 swine',
85: 'Swineherd Crook (reach, awkward, 1 wt), 1d4 swine',
86: 'Swineherd Crook (reach, awkward, 1 wt), 1d4 swine',
87: 'Tanner Knife (hand, 0 wt), 2d4 animal hides (2 wt)',
88: 'Thatcher Handaxe (close, 1 wt), 1d4 sheaves of straw (1 wt ea.)',
89: 'Tinker Tinkers tools (0 wt)',
90: 'Trapper Knife (hand, 0 wt), traps [roll 1D4: 1 = 2d4 rat traps (0 wt); 2 = 1d4 rabbit traps (2 wt); 3 = 1 snare trap (1 wt); 4 = 1 bear trap (2 wt)',
91: 'Trapper Knife (hand, 0 wt), traps [roll 1D4: 1 = 2d4 rat traps (0 wt); 2 = 1d4 rabbit traps (2 wt); 3 = 1 snare trap (1 wt); 4 = 1 bear trap (2 wt)',
92: 'Trapper Knife (hand, 0 wt), traps [roll 1D4: 1 = 2d4 rat traps (0 wt); 2 = 1d4 rabbit traps (2 wt); 3 = 1 snare trap (1 wt); 4 = 1 bear trap (2 wt)',
93: 'Undertaker Holy symbol (0 wt), coffin (4 wt)',
94: 'Watchman Spear (reach, thrown, near, 1 wt), helmet (worn, 0 wt), lantern (0 wt), flask of oil (0 wt), flint & steel (0 wt), horn (0 wt)',
95: 'Watchman Spear (reach, thrown, near, 1 wt), helmet (worn, 0 wt), lantern (0 wt), flask of oil (0 wt), flint & steel (0 wt), horn (0 wt)',
96: 'Watchman Spear (reach, thrown, near, 1 wt), helmet (worn, 0 wt), lantern (0 wt), flask of oil (0 wt), flint & steel (0 wt), horn (0 wt)',
97: 'Weaver 1d4 bolts of fabric (1 wt ea.)',
98: 'Woodsman Handaxe (close, 1 wt), 2d4 sticks of firewood (1 wt ea.)',
99: 'Woodsman Handaxe (close, 1 wt), 2d4 sticks of firewood (1 wt ea.)',
100: 'Woodsman Handaxe (close, 1 wt), 2d4 sticks of firewood (1 wt ea.)'
}
